"""initial migration

Revision ID: c79519a4a683
Revises:
Create Date: 2026-03-10 21:57:49.864499

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c79519a4a683"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect as sa_inspect

    bind = op.get_bind()
    inspector = sa_inspect(bind)
    existing_tables = inspector.get_table_names()

    if "results" in existing_tables:
        # Tables already exist (e.g. from a previous run); just stamp and return.
        return

    op.create_table(
        "results",
        sa.Column("result_id", sa.String(length=64), nullable=False),
        sa.Column("experiment_id", sa.String(length=64), nullable=False),
        sa.Column("trial_number", sa.Integer(), nullable=False),
        sa.Column("application", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("configured_capacity", sa.Float(), nullable=True),
        sa.Column("configured_latency", sa.Float(), nullable=True),
        sa.Column("measured_throughput", sa.Float(), nullable=True),
        sa.Column("measured_rtt", sa.Float(), nullable=True),
        sa.Column(
            "qoe_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "transport_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "contextual_tree", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("pcap_path", sa.String(length=512), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("result_id"),
    )
    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.create_index(
            "idx_exp_app_date",
            ["experiment_id", "application", "created_at"],
            unique=False,
        )

    op.create_table(
        "artifacts",
        sa.Column("artifact_id", sa.String(length=64), nullable=False),
        sa.Column("result_id", sa.String(length=64), nullable=False),
        sa.Column("artifact_type", sa.String(length=32), nullable=True),
        sa.Column("filename", sa.String(length=256), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("storage_path", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["results.result_id"],
        ),
        sa.PrimaryKeyConstraint("artifact_id"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(
            "idx_artifact_result_type", ["result_id", "artifact_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index("idx_artifact_result_type")

    op.drop_table("artifacts")
    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.drop_index("idx_exp_app_date")

    op.drop_table("results")
    # ### end Alembic commands ###
