"""human-cursor — Human-like mouse movements for Playwright (Python)."""

from .math_utils import Vector, TimedVector, ORIGIN, scale, clamp
from .tweening import (
    TweeningFunction,
    TWEEN_OPTIONS,
    linear,
    ease_in_quad,
    ease_out_quad,
    ease_in_out_quad,
    ease_in_cubic,
    ease_out_cubic,
    ease_in_out_cubic,
    ease_in_quart,
    ease_out_quart,
    ease_in_out_quart,
    ease_in_quint,
    ease_out_quint,
    ease_in_out_quint,
    ease_in_sine,
    ease_out_sine,
    ease_in_out_sine,
    ease_in_expo,
    ease_out_expo,
    ease_in_out_expo,
    ease_in_circ,
    ease_out_circ,
    ease_in_out_circ,
)
from .bezier_calculator import calculate_points_in_curve
from .human_curve_generator import HumanizeMouseTrajectory
from .mouse_helper import install_mouse_helper, install_mouse_helper_async
from .cursor import (
    GhostCursor,
    create_cursor,
    BoundingBox,
    BoxOptions,
    GetElementOptions,
    ScrollOptions,
    ScrollIntoViewOptions,
    MoveOptions,
    ClickOptions,
    MoveToOptions,
    get_element_box,
    get_random_page_point,
)

__all__ = [
    # Core
    "create_cursor",
    "GhostCursor",
    # Types
    "Vector",
    "TimedVector",
    "BoundingBox",
    "ORIGIN",
    # Options
    "BoxOptions",
    "GetElementOptions",
    "ScrollOptions",
    "ScrollIntoViewOptions",
    "MoveOptions",
    "ClickOptions",
    "MoveToOptions",
    # Utilities
    "install_mouse_helper",
    "install_mouse_helper_async",
    "get_element_box",
    "get_random_page_point",
    "calculate_points_in_curve",
    "HumanizeMouseTrajectory",
    # Tweening
    "TweeningFunction",
    "TWEEN_OPTIONS",
    "linear",
    "ease_in_quad",
    "ease_out_quad",
    "ease_in_out_quad",
    "ease_in_cubic",
    "ease_out_cubic",
    "ease_in_out_cubic",
    "ease_in_quart",
    "ease_out_quart",
    "ease_in_out_quart",
    "ease_in_quint",
    "ease_out_quint",
    "ease_in_out_quint",
    "ease_in_sine",
    "ease_out_sine",
    "ease_in_out_sine",
    "ease_in_expo",
    "ease_out_expo",
    "ease_in_out_expo",
    "ease_in_circ",
    "ease_out_circ",
    "ease_in_out_circ",
    # Math
    "scale",
    "clamp",
]
