"""OpenClaw skill definitions and executor (Step 10)."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from app.engine.experiment_generator import ExperimentGenerator
from app.models.schemas import GeneratedExperiment


_SKILL_HEADER_RE = re.compile(r"^##\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*$")


def _skills_md_path() -> Path:
    return Path(__file__).resolve().parents[2] / "SKILLS.md"


def load_skills() -> list[dict[str, Any]]:
    """Parse SKILLS.md into a concise machine-readable list."""
    lines = _skills_md_path().read_text().splitlines()
    skills: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None

    for raw in lines:
        line = raw.strip()
        header = _SKILL_HEADER_RE.match(line)
        if header:
            if current is not None:
                skills.append(current)
            current = {
                "name": header.group(1),
                "description": "",
            }
            continue

        if current is None:
            continue

        if line.startswith("Run ") or line.startswith("Compare ") or line.startswith(
            "Test "
        ):
            current["description"] = line

    if current is not None:
        skills.append(current)
    return skills


def _expand_range(range_cfg: dict[str, Any]) -> list[float]:
    minimum = float(range_cfg["min"])
    maximum = float(range_cfg["max"])
    step = float(range_cfg["step"])
    if step <= 0:
        raise ValueError("Range step must be > 0")
    values: list[float] = []
    value = minimum
    while value <= maximum + 1e-9:
        values.append(round(value, 6))
        value += step
    return values


class SkillExecutor:
    """High-level multi-step workflows that produce GeneratedExperiment lists."""

    def __init__(self) -> None:
        self.generator = ExperimentGenerator()

    def execute_parameter_sweep(self, params: dict[str, Any]) -> list[GeneratedExperiment]:
        capacities: list[float]
        latencies: list[float]
        if "capacity_values" in params:
            capacities = [float(v) for v in params["capacity_values"]]
        else:
            capacities = _expand_range(params["capacity_range"])

        if "latency_values" in params:
            latencies = [float(v) for v in params["latency_values"]]
        else:
            latencies = _expand_range(params["latency_range"])

        parsed = {
            "applications": params["applications"],
            "capacities": capacities,
            "latencies": latencies,
            "cc_algorithms": params.get("cc_algorithms"),
            "aqm_policy": params.get("aqm_policy"),
            "duration_seconds": params.get("duration_seconds"),
            "num_trials": params.get("num_trials", 1),
            "ctp_cluster": params.get("ctp_cluster"),
            "reasoning": "Generated by skill: parameter_sweep",
        }
        return self.generator.generate(parsed)

    def execute_application_comparison(
        self, params: dict[str, Any]
    ) -> list[GeneratedExperiment]:
        parsed = {
            "applications": params["applications"],
            "capacities": [float(params["capacity_mbps"])],
            "latencies": [float(params["latency_ms"])],
            "cc_algorithms": (
                [params["cc_algorithm"]] if params.get("cc_algorithm") else None
            ),
            "aqm_policy": params.get("aqm_policy"),
            "duration_seconds": params.get("duration_seconds"),
            "num_trials": params.get("num_trials", 1),
            "ctp_cluster": params.get("ctp_cluster"),
            "reasoning": "Generated by skill: application_comparison",
        }
        return self.generator.generate(parsed)

    def execute_baseline(self, params: dict[str, Any]) -> list[GeneratedExperiment]:
        parsed = {
            "applications": params["applications"],
            "capacities": [1000.0],
            "latencies": [5.0],
            "cc_algorithms": (
                [params["cc_algorithm"]] if params.get("cc_algorithm") else ["cubic"]
            ),
            "aqm_policy": params.get("aqm_policy", "fifo"),
            "duration_seconds": params.get("duration_seconds"),
            "num_trials": params.get("num_trials", 1),
            "ctp_cluster": params.get("ctp_cluster"),
            "reasoning": "Generated by skill: baseline_establishment",
        }
        return self.generator.generate(parsed)

    def execute_network_characterization(
        self, params: dict[str, Any]
    ) -> list[GeneratedExperiment]:
        parsed = {
            "applications": params["applications"],
            "capacities": [float(v) for v in params["capacity_values"]],
            "latencies": [float(v) for v in params["latency_values"]],
            "cc_algorithms": params.get("cc_algorithms"),
            "aqm_policy": params.get("aqm_policy"),
            "duration_seconds": params.get("duration_seconds"),
            "num_trials": params.get("num_trials", 1),
            "ctp_cluster": params.get("ctp_cluster"),
            "reasoning": "Generated by skill: network_characterization",
        }
        return self.generator.generate(parsed)

    def execute_replicate_study(self, params: dict[str, Any]) -> list[GeneratedExperiment]:
        matrix = params["matrix"]
        parsed = {
            "applications": matrix["applications"],
            "capacities": matrix["capacities"],
            "latencies": matrix["latencies"],
            "cc_algorithms": matrix.get("cc_algorithms"),
            "aqm_policy": matrix.get("aqm_policy"),
            "duration_seconds": matrix.get("duration_seconds"),
            "num_trials": params.get("num_trials", matrix.get("num_trials", 1)),
            "ctp_cluster": matrix.get("ctp_cluster"),
            "reasoning": f"Generated by skill: replicate_study ({params.get('study_name', 'custom')})",
        }
        return self.generator.generate(parsed)

